# -----------------------
# ~/.config/starship.toml
# -----------------------

# add_newline = false      # Inserts blank line between shell prompts. Default = true
# command_timeout = 500    # Timeout for commands executed by starship (in milliseconds).
# scan_timeout = 30        # Timeout for starship to scan files (in milliseconds).

format="""
[(\
[  ](ubuntu_orange bg:bgcolor1)\
$time\
$battery\
 )](bgcolor1)\
$all\
$fill\
$shlvl\
[(\
$shell\
$username\
$hostname\
$localip\
 )](bgcolor2)\
$line_break\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$kubernetes\
$line_break\
$cmd_duration\
$status\
$character\
"""

right_format="""
$aws\
$gcloud\
$azure\
"""

# -----------------------
# COLOR PALETTE
# -----------------------
palette = "custom1"

[palettes.custom1]
# white = '#ffffff'
# black = '#000000'
bgcolor1 = 'black'
bgcolor2 = 'bright-black'
ubuntu_orange = '#E95420'
ubuntu_light_aubergine = '#77216F'
ubuntu_mid_aubergine = '#5E2750'
ubuntu_dark_aubergine = '#2C001E'
ubuntu_warm_grey = '#AEA79F'
ubuntu_cool_grey = '#333333'
ubuntu_text_grey = '#111111'
canonical_aubergine = '#772953'

# -----------------------
# MODULES
# -----------------------

[aws]
disabled = true
format = 'on [$symbol($profile )[(\($region\) )]($style dimmed)(\[$duration\])]($style) '
# format = '([](bgcolor)[$symbol($profile )[(\($region\) )]($style dimmed)(\[$duration\])]($style)[](bgcolor) )'
# style = 'bold yellow bg:bgcolor'
symbol = ' '

[azure]
disabled = true
format = 'on [$symbol($subscription)]($style) '
# format = '([](bgcolor)[$symbol($subscription)]($style)[](bgcolor) )'
# style = 'bold blue bg:bgcolor'
symbol = ' '

[battery]
format = '[ $symbol$percentage]($style bg:bgcolor1)'

[[battery.display]]
threshold = 100

[character]
format = '$symbol '
# success_symbol = '[](bold green)'
# error_symbol = '[](bold red)'
# success_symbol = '[❯](bold green)'
# error_symbol = '[❯](bold red)'

[directory]
truncation_length = 8
truncation_symbol = '…/'
# style = 'bold cyan italic'
home_symbol = ' ~'

[docker_context]
only_with_files = false

[fill]
symbol = ' '
style= 'dimmed white'

[gcloud]
disabled = true
format = 'on [$symbol($project )[\($region\)]($style dimmed)]($style) '
# format = 'on [$symbol($account(@$domain) )[(\($region\) \($project\))]($style dimmed)]($style) '
# format = '([](bgcolor)[$symbol($account(@$domain) )[(\($region\) \($project\))]($style dimmed)]($style)[](bgcolor) )'
# style = 'bold blue bg:bgcolor'
symbol = ' '

[hostname]
ssh_only = false
format = '[[@](bg:bgcolor2)$ssh_symbol$hostname]($style bg:bgcolor2)'
style = 'bold bright-green'

[kubernetes]
disabled = false
format = '([$symbol$context[( \($namespace\))]($style dimmed)]($style) )'
# format = '([](bgcolor)[$symbol$context[( \($namespace\))]($style dimmed bg:bgcolor)]($style)[](bgcolor) )'
# style = 'bold green bg:bgcolor'
style = 'bold green'
# symbol = '⎈ '
symbol = 'ﴱ '
# symbol = '☸️'

[kubernetes.context_aliases]
'.*cluster/(.*)' = '$1'

[localip]
ssh_only = false
disabled = false
# format = '([$localipv4]($style) )'
# format = '([](bgcolor)[$localipv4]($style bg:bgcolor)[](bgcolor) )'
format = '[[ \[](bg:bgcolor2)$localipv4[\]](bg:bgcolor2)]($style bg:bgcolor2)'
style = 'bold bright-purple'

[shell]
disabled = false
fish_indicator = '🐟'
bash_indicator = ' '
zsh_indicator = '🚀'
powershell_indicator = ' '
unknown_indicator = ' '
format  = '[$indicator ]($style bg:bgcolor2)'

[shlvl]
disabled = false
# format = '[$symbol]($style) '
# symbol = ''
# symbol = '❯'
symbol = ''
# repeat = true
# threshold = 1

[status]
disabled = false
symbol = ' '
# symbol = ' '
map_symbol = true
pipestatus = true

[time]
disabled = false
format = '[ $time]($style bg:bgcolor1)'
# style = 'bold bright-yellow'

[username]
show_always = true
format = '[$user]($style bg:bgcolor2)'
style_user = 'bold bright-yellow'
