# ~/.config/starship.toml

# Disable the blank line at the start of the prompt
# add_newline = false

format = '''$all
$directory
$character'''
right_format = '$battery$time'

[[battery.display]]
threshold = 100

[directory]
truncation_length = 8
truncation_symbol = '…/'

[docker_context]
only_with_files = false

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[kubernetes.context_aliases]
'.*cluster/(.*)' = '$1'

[time]
disabled = false
