[general]
import = [
  "style.toml",
  "theme-preview.toml",
]

[window]
opacity = 1.0

[env]
# https://github.com/alacritty/alacritty-theme
# We use Alacritty's default Linux config directory as our storage location here.
#   mkdir -p ~/.config/alacritty/themes
#   git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
ALACRITTY_THEME_PATH="themes/themes"
